config/routes.rb
PrototypeKDE::Application.routes.draw do

  resources :projects do
    get 'bug',:on=>:member
    get 'git',:on=>:member
    get 'mailList',:on=>:member
    get 'ircChannel',:on=>:member
  end

  get "home/index"
  get "/general_report", :to => "home#general_report"

  root :to => 'home#index' 

end

app/models/project.rb
require 'open-uri'
require 'feedzirra'
require 'git'

def search_bugzilla include_fields,limit=0,offset=0,getAll=false,creation_time = nil
  full_string = 'https://bugs.kde.org/jsonrpc.cgi?method=Bug.search&params=[{"product":'+convert_array_to_string_array(get_array(bugLists))+',"include_fields":'+ convert_array_to_string_array(include_fields)
  full_string += ',"status":["UNCONFIRMED","CONFIRMED","ASSIGNED","REOPENED"]' if !getAll
  full_string += ',"limit":'+limit.to_s+',"offset":'+offset.to_s if limit != 0
  full_string += ',"creation_time":"'+ get_time_as_string(creation_time) +'"' if creation_time
  full_string += '}]'
  unparsed = open(URI::encode(full_string))
  parsed = ActiveSupport::JSON.decode(unparsed)
  return parsed["result"]["bugs"] if parsed["result"]
  Rails.cache.write "error", parsed["error"]
end

def get_time_as_string time
  return time.strftime("%Y-%m-%dT%H:%M:%SZ")
end

def get_array text_to_parse
  return text_to_parse.split("\n")
end

def convert_array_to_string_array to_convert
  converted = "["
  to_convert.each do |element| 
    converted += '"' + element.chomp + '",'
  end
  return converted + "]" if converted.length == 1
  return converted[0..-2] + "]"
end


def count_bugs
  is_successful = search_bugzilla []
  if is_successful
    num = is_successful.length
    Rails.cache.write('numBugs'+id.to_s , [num,Time.now])
    return true
  end
  return false
end


def search_git product_name
  full_string = "http://quickgit.kde.org/?p="
  full_string += product_name.chomp
  full_string += "&a=atom"
  feed = Feedzirra::Feed.fetch_and_parse(full_string)
  return [] unless feed
  unless Rails.cache.read("last_commit"+id.to_s)
    Rails.cache.write("last_commit"+id.to_s,[feed.entries.first.id,feed.last_modified])
  else
    Rails.cache.write("last_commit"+id.to_s,[feed.entries.first.id,feed.last_modified]) if feed.last_modified > Rails.cache.read("last_commit"+id.to_s)[1]
  end
  return feed.entries
end

def search_commits limit = nil
  begin
  the_array = get_array(gitRepositories)
  rescue Exception
    return nil
  end
  commits = []
  the_array.each { |product|
    begin
      g = Git.bare('.', { :repository => 'gitMirror/' + product ,:index => '.' })
      g.log(limit).each { |commit|
	commits << commit
    }
    rescue Exception
    end
  }
  return commits
end


class Project < ActiveRecord::Base
  attr_accessible :bugLists, :describtion, :gitRepositories, :ircChannels, :mailLists, :name
  
  def test_git
    commits = []
    the_array = get_array(gitRepositories)
    the_array.each { |product|
      entries = search_git product
      entries.each { |entry|
	commits << entry
      }
    }
    return commits
  end
  
  def fetch_project_repos 
    the_array = get_array(gitRepositories)
    the_array.each { |product|
      g = Git.clone('git://anongit.kde.org/'+product.chomp, 'gitMirror/' + product.chomp, :bare => true)
      #add rescue
    }
  end
  handle_asynchronously :fetch_project_repos
  
  def commits_per_author
    commits = Rails.cache.read("commits_per_author"+id.to_s)
    return commits if commits
    successful = search_commits
    return nil unless successful
    commits = Hash.new(0)
    successful.each do |commit|
      commits[commit.author.name] += 1
    end  
    Rails.cache.write("commits_per_author"+id.to_s,commits) unless commits.length == 0
    return commits
  end
  
  def array_repos
    return get_array(gitRepositories)
  end
  
  def number_of_bugs
    num = Rails.cache.read('numBugs'+id.to_s)
    #if num
    #  return num[0] if search_bugzilla([],0,0,false,num[1]).length == 0
    #end
    return num[0] if num
    if count_bugs
      return Rails.cache.read('numBugs'+id.to_s)[0]
    end
    return "Not found."
  end
    
  # gets limited number of bugs but with all needed attributes.
  def limited_bugs offset, number = 10
    if !offset
      offset = 1
    end
    is_successful = search_bugzilla ["id","assigned_to","component","last_change_time","status","summary"],number,(offset.to_i-1)*10
    return is_successful if is_successful
    return []
  end
  
  def latest_bug 
    latest = Rails.cache.read("latest_bug"+id.to_s)
    return latest if latest
    successful = search_bugzilla ["id","creation_time"]
    last = successful[0]
    unless last 
      Rails.cache.write("latest_bug"+id.to_s,"")
      return ""
    end
    successful.each { |bug|
      if bug["creation_time"] > last["creation_time"]
	last = bug
      end
    }
    Rails.cache.write("latest_bug"+id.to_s,last)
    return last
  end
  
  def bugs_by_state
    bugs = Rails.cache.read("bugsFor"+id.to_s)
    return bugs[0] if bugs
    successful = search_bugzilla ["id","status"],0,0,true
    return nil unless successful
    bugs = Hash.new(0)
    successful.each do |bug|
      bugs[bug["status"]] += 1
      end  
      Rails.cache.write("bugsFor"+id.to_s,[bugs,Time.now])
    return bugs
  end
  
  def latest_commit
    latest = Rails.cache.read("last_commit"+id.to_s)
    return latest if latest
    return Rails.cache.read("last_commit"+id.to_s) if test_git != []
    return ["",""]
  end
  
  
  def prepare_commits_line_graphs_all_time
    product = git_repos.chomp
    res_commits = Array.new
    the_array = Project.repo(product).log(nil).to_a.reverse
    first = the_array.shift
    Rails.cache.write("first_date_commits"+id.to_s,first.date.to_i * 1000)
    res_commits << 1
    last_date = first.date.utc.strftime("%d%m%Y")
    the_array.each do |commit|
      this_date = commit.date.utc.strftime("%d%m%Y")
      if last_date == this_date
        res_commits[-1]+= 1 
      else
        temp_date = this_date
        last_date = DateTime.strptime(last_date,"%d%m%Y")
        this_date = DateTime.strptime(this_date,"%d%m%Y")
        ((this_date-last_date).to_i-1).times do 
          res_commits << 0
        end
        last_date = temp_date
        res_commits << 1
      end
    end
    ((DateTime.now.beginning_of_day-DateTime.strptime(last_date,"%d%m%Y")).to_i-1).times do
      res_commits << 0
      res_committers << 0
    end
    Rails.cache.write("commits_all_time"+id.to_s,res_commits)
  end
  
  
  def self.prepare_kde_facebook_report
    graph = Koala::Facebook::API.new("app_token_here")
    feed = graph.get_page("kde/feed")
    res = Array.new
    start_date = DateTime.parse(feed.first["created_time"])
    last_date = start_date.utc.strftime("%d%m%Y")
    starting_date = DateTime.now.to_i * 1000
    ((DateTime.now.beginning_of_day-DateTime.strptime(last_date,"%d%m%Y")).to_i).times do
      res << 0
    end
    res << 0
    while(feed.length != 0) 
      feed.each do |f|
	this_date = DateTime.parse(f["created_time"]).utc.strftime("%d%m%Y")
	if last_date == this_date
	  res[-1]+= 1 
	else
	  temp_date = this_date
	  last_date = DateTime.strptime(last_date,"%d%m%Y")
	  this_date = DateTime.strptime(this_date,"%d%m%Y")
	  ((last_date-this_date).to_i-1).times do 
	    res << 0
	  end
	  last_date = temp_date
	  res << 1
	end
      end
      starting_date = DateTime.parse(feed.last["created_time"]).utc.to_i * 1000
      feed = feed.next_page
    end
    db = FbStats.find_by_project_id(0)
    db.forum_start_date = starting_date.to_s
    db.forum_stats = res.reverse.to_s
    db.save
  end
  
  def self.prepare_total_forum_posts
    num = 0
    link = "https://forum.kde.org/search.php?keywords=&terms=all&author=&tags=&sv=0&sc=1&sf=titleonly&sk=t&sd=d&st=0&feed_type=RSS2.0&feed_style=COMPACT&countlimit=100&submit=Search"
    feed = Feedzirra::Feed.fetch_and_parse(link).entries
    res = Array.new
    start_date = DateTime.parse(feed.first.published.to_s)
    last_date = start_date.utc.strftime("%d%m%Y")
    starting_date = DateTime.now.to_i * 1000
    ((DateTime.now.beginning_of_day-DateTime.strptime(last_date,"%d%m%Y")).to_i).times do
      res << 0
    end
    res << 0
    while(true) 
      feed.each do |f|
	this_date = DateTime.parse(f.published.to_s).utc.strftime("%d%m%Y")
	if last_date == this_date
	  res[-1]+= 1 
	else
	  temp_date = this_date
	  last_date = DateTime.strptime(last_date,"%d%m%Y")
	  this_date = DateTime.strptime(this_date,"%d%m%Y")
	  ((last_date-this_date).to_i-1).times do 
	    res << 0
	  end
	  last_date = temp_date
	  res << 1
	end
      end
      starting_date = DateTime.parse(feed.last.published.to_s).utc.to_i * 1000
      if feed.length == 100
	num+= 100
      else
	num+= feed.length+1
      end
      link = "https://forum.kde.org/search.php?keywords=&terms=all&author=&tags=&sv=0&sc=1&sf=titleonly&sk=t&sd=d&st=0&feed_type=RSS2.0&feed_style=COMPACT&countlimit=100&submit=Search&start=#{num}"
      begin
	feed = Feedzirra::Feed.fetch_and_parse(link).entries
      rescue
	break
      end
    end
    db = FbStats.find_by_project_id(0)
    db.forum_start_date = starting_date.to_s
    db.forum_stats = res.reverse.to_s
    db.save
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.paginate(:page => params[:page],:per_page => 20)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @bugs_by_state = @project.bugs_by_state
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bugs_by_state}
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @projects = Project.find(:all, :order => "id desc", :limit => 10)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @projects = Project.find(:all, :order => "id desc", :limit => 10)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    respond_to do |format|
      if @project.save
	@project.fetch_project_repos
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    @temp = @project.gitRepositories
    respond_to do |format|
      if @project.update_attributes(params[:project])
	if @temp != @project
	  @project.fetch_project_repos
	  Rails.cache.delete("commits_per_author"+@project.id.to_s)
	end
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  def bug
    @project = Project.find(params[:id])
    @bugs = @project.limited_bugs(params[:page],10)
    @numBugs = Array.new(@project.number_of_bugs,nil)
    @bugsPages = @numBugs.paginate(:page => params[:page],:per_page => 10)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bugs }
    end
  end
  
  def git
    @project = Project.find(params[:id])
    @git = @project.test_git
  end
  
  def mailList
    @project = Project.find(params[:id])
  end
  
  def ircChannel
    @project = Project.find(params[:id])
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :describtion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :describtion, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bugLists, :class => 'control-label' %> 
    <div class="controls">
      <%= f.text_area :bugLists, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gitRepositories, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :gitRepositories, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mailLists, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :mailLists, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ircChannels, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :ircChannels, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/_sidebar.html.erb
    <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header"><%= @project.name %></li>
              <li><%= link_to t('project_page'), project_path %></li>
              <li><%= link_to t('bug_report'), bug_project_path %></li>
              <li><%= link_to t('git_report'), git_project_path %></li>
              <li class="disabled"><%= link_to t('mailList_report'), mailList_project_path %></li>
              <li class="disabled"><%= link_to t('irc_report'), ircChannel_project_path %></li>
            </ul>
    </div>

app/views/projects/bug.html.erb
<div class="page-header">
  <h1 class="text-center"><%= @project.name.upcase %> <%= t :bugs %></h1>
</div>
<div class="row-fluid">
  <div class="span3">
    <%= render :partial => 'sidebar' %>
  </div>
  <div class="span9">    
    <table class="table table-striped">
      <thead>
	<tr>
	  <th class="bugsTableHead"><%= t :id %></th>
	  <th class="bugsTableHead"><%= t :component %></th>
	  <th class="bugsTableHead"><%= t :assignee %></th>
	  <th class="bugsTableHead"><%= t :status %></th>
	  <th class="bugsTableHead"><%= t :summary %></th>
	  <th class="bugsTableHead"><%= t :changed %></th>
	</tr>
      </thead>
      <tbody>
	<% @bugs.each do |bug| %>
	  <tr>
	    <td class="bugsTable"><a href="https://bugs.kde.org/show_bug.cgi?id=<%= bug["id"] %>"><%= bug["id"] %></a></td>
	    <td class="bugsTable"><%= bug["component"] %></td>
	    <td class="bugsTable"><%= bug["assigned_to"] %></td>
	    <td class="bugsTable"><%= bug["status"] %></td>
	    <td class="bugsTable"><%= bug["summary"] %></td>
	    <td class="bugsTable"><%= bug["last_change_time"][0..9] %></td>
	  </tr>
	<% end %>
      </tbody>
    </table>
    <%= will_paginate @bugsPages, :renderer => BootstrapPagination::Rails %>
  </div>
</div>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class = "page-header">
  <h1>Edit <%= @project.name %></h1>
</div>

<div class = "row-fluid">
  <div class = "span5">
    <div class="well well-large">
      <h2>Latest Projects</h2>
      <ul>
	<% @projects.each do |project| %>
	  <li>
	    <%= link_to project.name, project_path(project) %>
	  </li>
	<% end %>
      </ul>
    </div>
  </div>
  <div class = "span7">
    <div class = "well well-large">
      <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/projects/git.html.erb
<div class="page-header">
  <h1 class="text-center"><%= @project.name.upcase %> Git Repositories</h1>
</div>
<div class="row-fluid">
  <div class="span3">
    <%= render :partial => 'sidebar' %>
  </div>
  <div class="span9">
  <% @project.array_repos.each do |repo| %>
    <div class="well well-small">
      <div class="btn-group">
	<button class="btn"><%= t :git %></button>
	<input type="text" style="width:400px;background-color:white;" onClick="this.select();" class="text_field" value="git://anongit.kde.org/<%= repo %>" readonly>
      </div>
    </div>
  <% end %>
    <table class="table table-striped">
      <thead>
	<tr>
	  <th><%= t :id %></th>
	  <th><%= t :title %></th>
	  <th><%= t :author %></th>
	  <th><%= t :date_time %></th>
	  <th><%= t :files_changed %></th>
	</tr>
      </thead>
      <tbody>
	<% @git.each do |commit| %>
	  <tr>
	    <td><a href="<%= commit.id %>"><%= commit.id[commit.id.index('h=')+2..commit.id.index('h=')+9] %></a></td>
	    <td><%= commit.title %></td>
	    <td><%= commit.author %></td>
	    <td><%= commit.published.to_s[0..18] %></td>
	    <td><%= commit.content.scan("\n").length-8 %></td>
	  </tr>
	<% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human(count: 3) %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:describtion) %></th>
      <th><%= t :number_of_bugs %></th>
      <th><%= t :latest_reported_bug %></th>
      <th><%= t :latest_commit %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= project.describtion %></td>
        <td><%= project.number_of_bugs %></td>
        <td><a href="https://bugs.kde.org/show_bug.cgi?id=<%= project.latest_bug["id"] %>"><%= project.latest_bug["creation_time"][0..9] if project.latest_bug["creation_time"] %></a></td>
        <td><a href="<%= project.latest_commit[0] %>"><%= project.latest_commit[1].to_s[0..-4] %></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @projects %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/ircChannel.html.erb
<div class="page-header">
  <h1 class="text-center"><%= @project.name.upcase %> IRC Channels</h1>
</div>
<div class="row-fluid">
  <div class="span3">
    <%= render :partial => 'sidebar' %>
  </div>
  <div class="span9">
    <div class="hero-unit">
      <h1>You shouldn't be HERE!</h1>
      <p>A big Monster might eat YOU!</p>
      <p>
	<a class="btn btn-primary btn-large" href="http://www.wallpaperdev.com/customres/1024x768-hd-dakar-monster-energy-cars-tacspx-wallpapers-free.jpg">
	  RUN NOW!!!
	</a>
      </p>
    </div>
  </div>
</div>

app/views/projects/mailList.html.erb
<div class="page-header">
  <h1 class="text-center"><%= @project.name.upcase %> Mail Lists</h1>
</div>
<div class="row-fluid">
  <div class="span3">
    <%= render :partial => 'sidebar' %>
  </div>
  <div class="span9">
    <div class="hero-unit">
      <h1>You shouldn't be HERE!</h1>
      <p>A big Monster might eat YOU!</p>
      <p>
	<a class="btn btn-primary btn-large" href="http://www.wallpaperdev.com/customres/1024x768-hd-dakar-monster-energy-cars-tacspx-wallpapers-free.jpg">
	  RUN NOW!!!
	</a>
      </p>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%- model_class = Project -%>

<div class = "page-header">
  <h1><%= t :new_project %></h1>
</div>

<div class = "row-fluid">
  <div class = "span5">
    <div class="well well-large">
      <h2><%= t :latest_projects %></h2>
      <ul>
	<% @projects.each do |project| %>
	  <li>
	    <%= link_to project.name, project_path(project) %>
	  </li>
	<% end %>
      </ul>
    </div>
  </div>
  <div class = "span7">
    <div class = "well well-large">
      <h1><%= t :new %></h1>
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1 class="text-center"> <%= model_class.model_name.human(count:1) %>: <%= @project.name.upcase %></h1>
</div>

<div class="row-fluid">
  <div class="span3">
    <%= render :partial => 'sidebar' %>
  </div>
  <div class="span9">
    <div class="well well-small">
      <h3><%= t :bugs %>:</h3>
      <table class="table table-striped">
	<thead>
	  <tr>
	    <th class="bugsTableHead"><%= t :confirmed %></th>
	    <th class="bugsTableHead"><%= t :unconfirmed %></th>
	    <th class="bugsTableHead"><%= t :assigned %></th>
	    <th class="bugsTableHead"><%= t :reopened %></th>
	    <th class="bugsTableHead"><%= t :resolved %></th>
	    <th class="bugsTableHead"><%= t :needsinfo %></th>
	    <th class="bugsTableHead"><%= t :verified %></th>
	  </tr>
	</thead>
	<tbody>
	  <tr>
	    <td class="bugsTable"><%= @bugs_by_state["CONFIRMED"] %></td>
	    <td class="bugsTable"><%= @bugs_by_state["UNCONFIRMED"] %></td>
	    <td class="bugsTable"><%= @bugs_by_state["ASSIGNED"] %></td>
	    <td class="bugsTable"><%= @bugs_by_state["REOPENED"] %></td>
	    <td class="bugsTable"><%= @bugs_by_state["RESOLVED"] %></td>
	    <td class="bugsTable"><%= @bugs_by_state["NEEDSINFO"] %></td>
	    <td class="bugsTable"><%= @bugs_by_state["VERIFIED"] %></td>
	  </tr>
	</tbody>
      </table>     
      <div id="bug_chart" style="height:400px;" class="well well-large">
      </div>
    </div>
    <div class = "well well-small">
      <h3><%= t :git %>:</h3>
      <div id="commit_chart" style="height:400px;" class="well well-large">
      </div>
    </div>
    <div class = "well well-small">
      <h3><%= t :mailLists %>:</h3>
      <p><%= t :under_construction %>.</p>
    </div>
    <div class = "well well-small">
      <h3><%= t :irc_channels %>:</h3>
      <p><%= t :under_construction %>.</p>
    </div>
      <div class="form-actions">
	<%= link_to t('.back', :default => t("helpers.links.back")),
		    projects_path, :class => 'btn'  %>
	<%= link_to t('.edit', :default => t("helpers.links.edit")),
		    edit_project_path(@project), :class => 'btn' %>
	<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
		    project_path(@project),
		    :method => 'delete',
		    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
		    :class => 'btn btn-danger' %>
      </div>
  </div>
</div>
<% content_for :scripts do %>
  <script>
    $(function() {
      new Highcharts.Chart({
      chart: {
	renderTo: "bug_chart"
      },
      title: {
	text: "Bugs"
      },
      tooltip: {
	pointFormat: '<b>{point.y}</b>',
	percentageDecimals: 1
      },
      plotOptions: {
	pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        formatter: function() {
                            return '<b>'+ this.point.name +'</b>: '+ this.percentage.toFixed(1) +' %';
                        }
                    }
             }
      },
      series: [{
                type: 'pie',
                name: 'Bugs',
                data: [
		  <% @bugs_by_state.sort_by{|k,v| v}.each do |k,v| %>
		    <% if k == "CONFIRMED" %>
		      {
			name: '<%= k %>',
			y: <%= v %>,
			sliced: true,
			selected: true
		      },
		    <% else %>
		      ['<%= k %>',<%= v %>],
		    <% end %>
		  <% end %>
                ]
            }]
      });
      new Highcharts.Chart({
      chart: {
	renderTo: "commit_chart"
      },
      title: {
	text: "Total Commits"
      },
      tooltip: {
	pointFormat: '<b>{point.y}</b>',
	percentageDecimals: 1
      },
      plotOptions: {
	pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        formatter: function() {
                            return '<b>'+ this.point.name +'</b>: '+ this.percentage.toFixed(1) +' %';
                        }
                    }
             }
      },
      series: [{
                type: 'pie',
                name: 'Bugs',
                data: [
		  <% @project.commits_per_author.sort_by{|k,v| v}.each do |k,v| %>
		      ['<%= k %>',<%= v %>],
		  <% end %>
                ]
            }]
      });
    });
  </script>
<% end %>